apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: taskportal
type: Opaque
stringData:
  DB_PASSWORD: apppass
  DD_API_KEY: "your-datadog-api-key-here"
  DD_APP_KEY: "your-datadog-app-key-here"
